<?php
/**
 * This file contains InputRequired class.
 * Cette classe permet de définir des arguments & options requis.
 *
 * @author Akbly Sofiane <sakbly@pndata.tech>
 */

namespace PNdata\Copy\Commands\Input\Type;


use PNdata\Copy\Commands\Input\Input;

/**
 * Class InputRequired
 * @package PNdata\Copy\Commands\Input\Type
 * @see Input
 */
class InputRequired extends Input
{

    /**
     * @param string $name
     * @param bool $required
     * @param mixed|null $default
     * @param string $description
     * @return array
     * @see Input::value()
     */
    protected static function value(string $name, bool $required = true, $default = null, string $description = ''): array
    {
        return parent::value($name, $required, $default, $description); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $name
     * @param $default
     * @param string $description
     * @return array
     */
    public static function option(string $name, $default, $description = '')
    {
        return self::value($name, true, $default, $description);
    }

}